import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "This is Demo 1 page",
  description: "Generated by create next app",
};


const Demo1 = () => {
  return (
    <div>Demo1</div>
  )
}

export default Demo1