import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "This is Demo 2 Page",
  description: "Generated by create next app",
};


const Demo2 = () => {
  return (
    <div>Demo2</div>
  )
}

export default Demo2